import {fixtureReferenceTime} from '@/lib/fixture-clock';
import {approvedCompliance, documentStatus} from './compliance';
import type {DocumentSummary, DocumentsViewModel} from './types';

const documents: DocumentSummary[] = [
  {id: 'construct-pro-tax-2024', vendorId: 'construct-pro', vendorName: 'Construct Pro SRL', documentName: {ro: 'Certificat fiscal', en: 'Tax certificate'}, filename: 'Certificat_fiscal_CP_2024.pdf', documentType: 'tax', status: 'review', uploadedAt: '2026-10-01', expiresAt: '2026-10-07', reviewRoute: '/documents/construct-pro-tax-2024/review'},
  {id: 'construct-pro-registration-2024', vendorId: 'construct-pro', vendorName: 'Construct Pro SRL', documentName: {ro: 'Certificat de înregistrare', en: 'Registration certificate'}, filename: 'ONRC_2024.pdf', documentType: 'registration', status: 'valid', uploadedAt: '2026-09-30', expiresAt: null, reviewRoute: null},
  {id: 'construct-pro-fire-2024', vendorId: 'construct-pro', vendorName: 'Construct Pro SRL', documentName: {ro: 'Autorizație ISU', en: 'Fire safety authorization'}, filename: 'Autorizatie_ISU.pdf', documentType: 'fire', status: 'valid', uploadedAt: '2026-09-29', expiresAt: '2027-05-03', reviewRoute: null},
  {id: 'global-clean-insurance-2024', vendorId: 'global-clean', vendorName: 'Global Clean Services', documentName: {ro: 'Poliță RCA', en: 'Liability insurance policy'}, filename: 'RCA_2024.pdf', documentType: 'insurance', status: 'expiring', uploadedAt: '2026-09-28', expiresAt: '2026-10-07', reviewRoute: null},
  {id: 'tech-solutions-inspector-2024', vendorId: 'tech-solutions', vendorName: 'Tech Solutions SRL', documentName: {ro: 'Certificat constatator', en: 'Company status certificate'}, filename: 'Constatator_2024.pdf', documentType: 'inspector', status: 'valid', uploadedAt: '2026-09-27', expiresAt: null, reviewRoute: null},
  {id: 'global-clean-financial-2023', vendorId: 'global-clean', vendorName: 'Global Clean Services', documentName: {ro: 'Bilanț 2023', en: '2023 financial statements'}, filename: 'Bilant_2023.pdf', documentType: 'financial', status: 'review', uploadedAt: '2026-09-26', expiresAt: null, reviewRoute: null},
  {id: 'logistics-expert-tax-2023', vendorId: 'logistics-expert', vendorName: 'Logistics Expert', documentName: {ro: 'Certificat fiscal', en: 'Tax certificate'}, filename: 'Certificat_fiscal_2023.pdf', documentType: 'tax', status: 'expired', uploadedAt: '2026-06-10', expiresAt: '2026-09-30', reviewRoute: null},
  {id: 'build-more-environment-2024', vendorId: 'build-more', vendorName: 'Build & More SRL', documentName: {ro: 'Autorizație mediu', en: 'Environmental authorization'}, filename: 'Mediu_2024.pdf', documentType: 'environment', status: 'valid', uploadedAt: '2026-09-24', expiresAt: '2027-12-12', reviewRoute: null},
  {id: 'green-energy-safety-2024', vendorId: 'green-energy', vendorName: 'Green Energy SRL', documentName: {ro: 'Certificat SSM', en: 'Workplace safety certificate'}, filename: 'SSM_2024.pdf', documentType: 'safety', status: 'valid', uploadedAt: '2026-09-23', expiresAt: '2027-01-28', reviewRoute: null},
  {id: 'food-supplies-registration-2024', vendorId: 'food-supplies', vendorName: 'Food Supplies SRL', documentName: {ro: 'Certificat de înregistrare', en: 'Registration certificate'}, filename: 'ONRC_Food_2024.pdf', documentType: 'registration', status: 'valid', uploadedAt: '2026-09-22', expiresAt: null, reviewRoute: null},
  {id: 'medical-supplies-insurance-2024', vendorId: 'medical-supplies', vendorName: 'Medical Supplies', documentName: {ro: 'Poliță RCA', en: 'Liability insurance policy'}, filename: 'RCA_Medical_2024.pdf', documentType: 'insurance', status: 'review', uploadedAt: '2026-09-21', expiresAt: '2026-10-18', reviewRoute: null},
  {id: 'alpha-construction-tax-2024', vendorId: 'alpha-construction', vendorName: 'Alpha Construction SRL', documentName: {ro: 'Certificat fiscal', en: 'Tax certificate'}, filename: 'Fiscal_Alpha_2024.pdf', documentType: 'tax', status: 'valid', uploadedAt: '2026-09-20', expiresAt: '2027-07-14', reviewRoute: null},
  {id: 'nordic-software-financial-2023', vendorId: 'nordic-software', vendorName: 'Nordic Software SRL', documentName: {ro: 'Bilanț 2023', en: '2023 financial statements'}, filename: 'Bilant_Nordic_2023.pdf', documentType: 'financial', status: 'valid', uploadedAt: '2026-09-19', expiresAt: null, reviewRoute: null},
  {id: 'urban-logistics-fire-2024', vendorId: 'urban-logistics', vendorName: 'Urban Logistics SRL', documentName: {ro: 'Autorizație ISU', en: 'Fire safety authorization'}, filename: 'ISU_Urban_2024.pdf', documentType: 'fire', status: 'expiring', uploadedAt: '2026-09-18', expiresAt: '2026-10-15', reviewRoute: null},
  {id: 'eco-clean-environment-2024', vendorId: 'eco-clean', vendorName: 'Eco Clean Team SRL', documentName: {ro: 'Autorizație mediu', en: 'Environmental authorization'}, filename: 'Mediu_Eco_2024.pdf', documentType: 'environment', status: 'valid', uploadedAt: '2026-09-17', expiresAt: '2027-10-05', reviewRoute: null},
  {id: 'terra-materials-safety-2023', vendorId: 'terra-materials', vendorName: 'Terra Materials SRL', documentName: {ro: 'Certificat SSM', en: 'Workplace safety certificate'}, filename: 'SSM_Terra_2023.pdf', documentType: 'safety', status: 'expired', uploadedAt: '2026-01-10', expiresAt: '2026-01-10', reviewRoute: null},
  {id: 'solar-partners-inspector-2023', vendorId: 'solar-partners', vendorName: 'Solar Partners SRL', documentName: {ro: 'Certificat constatator', en: 'Company status certificate'}, filename: 'Constatator_Solar.pdf', documentType: 'inspector', status: 'valid', uploadedAt: '2026-09-15', expiresAt: null, reviewRoute: null},
  {id: 'fresh-food-insurance-2023', vendorId: 'fresh-food', vendorName: 'Fresh Food Distribution', documentName: {ro: 'Poliță RCA', en: 'Liability insurance policy'}, filename: 'RCA_Fresh_2023.pdf', documentType: 'insurance', status: 'expiring', uploadedAt: '2026-09-14', expiresAt: '2026-10-20', reviewRoute: null},
  {id: 'medica-plus-registration-2023', vendorId: 'medica-plus', vendorName: 'Medica Plus SRL', documentName: {ro: 'Certificat de înregistrare', en: 'Registration certificate'}, filename: 'ONRC_Medica.pdf', documentType: 'registration', status: 'valid', uploadedAt: '2026-09-13', expiresAt: null, reviewRoute: null},
  {id: 'delta-construct-tax-2023', vendorId: 'delta-construct', vendorName: 'Delta Construct SRL', documentName: {ro: 'Certificat fiscal', en: 'Tax certificate'}, filename: 'Fiscal_Delta_2023.pdf', documentType: 'tax', status: 'review', uploadedAt: '2026-09-12', expiresAt: '2026-10-25', reviewRoute: null},
  {id: 'digital-works-financial-2023', vendorId: 'digital-works', vendorName: 'Digital Works SRL', documentName: {ro: 'Bilanț 2023', en: '2023 financial statements'}, filename: 'Bilant_Digital_2023.pdf', documentType: 'financial', status: 'valid', uploadedAt: '2026-09-11', expiresAt: null, reviewRoute: null},
  {id: 'rapid-cargo-fire-2023', vendorId: 'rapid-cargo', vendorName: 'Rapid Cargo SRL', documentName: {ro: 'Autorizație ISU', en: 'Fire safety authorization'}, filename: 'ISU_Rapid_2023.pdf', documentType: 'fire', status: 'expiring', uploadedAt: '2026-09-10', expiresAt: '2026-10-27', reviewRoute: null},
  {id: 'prime-clean-environment-2023', vendorId: 'prime-clean', vendorName: 'Prime Clean SRL', documentName: {ro: 'Autorizație mediu', en: 'Environmental authorization'}, filename: 'Mediu_Prime_2023.pdf', documentType: 'environment', status: 'valid', uploadedAt: '2026-09-09', expiresAt: '2027-11-22', reviewRoute: null},
  {id: 'nova-energy-tax-2023', vendorId: 'nova-energy', vendorName: 'Nova Energy SRL', documentName: {ro: 'Certificat fiscal', en: 'Tax certificate'}, filename: 'Fiscal_Nova_2023.pdf', documentType: 'tax', status: 'valid', uploadedAt: '2026-08-12', expiresAt: '2027-11-15', reviewRoute: null}
].map((document) => ({...document, status: document.status === 'review' ? 'review' : documentStatus(approvedCompliance(document.expiresAt, 30, fixtureReferenceTime))})) as DocumentSummary[];

export const documentsFixture: DocumentsViewModel = {
  user: {fullName: 'Andrei Popescu', initials: 'AP'},
  organization: {name: 'Demo Company SRL'},
  notificationCount: 3,
  previousMonthCount: 22,
  documents
};
