import {expect, test, type Page} from '@playwright/test';
import {openFilters} from './support/filters';

async function addContact(page: Page, english: boolean, email = 'maria@example.test') {
  await page.getByRole('button', {name: english ? 'Add contact' : 'Adaugă contact', exact: true}).click();
  const drawer = page.getByRole('dialog', {name: english ? 'Add contact' : 'Adaugă contact', exact: true});
  await drawer.locator('#contact-name').fill(' Maria Ionescu ');
  await drawer.locator('#contact-email').fill(email);
  await drawer.locator('#contact-role').fill('Responsabil SSM');
  await drawer.locator('#contact-phone').fill('+40 721 234 567');
  await drawer.getByRole('button', {name: english ? 'Add contact' : 'Adaugă contact', exact: true}).click();
  return drawer;
}
async function createNote(page: Page, english: boolean, title: string) {
  await page.getByRole('button', {name: english ? 'Create a thread' : 'Creează un thread'}).click();
  await page.locator('#vendor-note-title').fill(title);
  await page.locator('#vendor-note-content').fill(`Content for ${title}`);
  await page.getByRole('button', {name: english ? 'Save changes' : 'Salvează modificările'}).click();
}
for (const english of [false, true]) {
  const prefix = english ? '/en' : '';
  test(`${english ? 'EN' : 'RO'} contacts: primary/edit/duplicate/delete and invitation recipient`, async ({page}) => {
    await page.goto(`${prefix}/vendors/construct-pro`);
    await page.getByRole('tab', {name: english ? 'Contacts' : 'Contacte', exact: true}).click();
    const primary = page.locator('[data-contact-id="contact:construct-pro:primary"]');
    await expect(primary).toContainText('Ion Popescu');
    await expect(primary).toContainText(english ? 'Primary' : 'Principal');
    let drawer = await addContact(page, english, ' ION.POPESCU@SCconstruct.RO ');
    await expect(drawer.getByRole('alert')).toContainText(english ? 'already exists' : 'Există deja');
    await drawer.locator('#contact-email').fill(' maria@example.test ');
    await drawer.getByRole('button', {name: english ? 'Add contact' : 'Adaugă contact', exact: true}).click();
    await expect(drawer).toHaveCount(0);
    const row = page.getByRole('row').filter({hasText: 'maria@example.test'});
    await expect(row).toContainText('Maria Ionescu');
    await row.getByRole('button').click();
    await page.getByRole('menuitem', {name: english ? 'Set as primary' : 'Setează ca principal'}).click();
    await expect(row).toHaveAttribute('data-primary', 'true');
    await expect(primary).toHaveAttribute('data-primary', 'false');
    await expect(page.getByRole('region', {name: english ? 'Supplier contact details' : 'Date de contact furnizor'})).toContainText('maria@example.test');
    await row.getByRole('button').click();
    await expect(page.getByRole('menuitem', {name: english ? 'Delete contact' : 'Șterge contactul'})).toHaveCount(0);
    await page.getByRole('menuitem', {name: english ? 'Edit contact' : 'Editează contact'}).click();
    drawer = page.getByRole('dialog');
    await drawer.locator('#contact-name').fill('Maria Updated');
    await drawer.locator('#contact-email').fill('updated@example.test');
    await drawer.getByRole('button', {name: english ? 'Save contact' : 'Salvează contactul'}).click();
    await expect(drawer).toHaveCount(0);
    await page.getByRole('button', {name: english ? 'Invite supplier' : 'Invită furnizor', exact: true}).click();
    const invite = page.getByRole('dialog');
    await expect(invite.locator('#invite-vendor-contact option:checked')).toContainText('Maria Updated — updated@example.test');
    await invite.locator('#invite-vendor-contact').selectOption('contact:construct-pro:primary');
    await invite.getByRole('button', {name: english ? 'Send invitation' : 'Trimite invitația'}).click();
    await expect(invite.getByRole('status')).toContainText(english ? 'no invitation was sent' : 'nu a fost trimisă');
    await page.keyboard.press('Escape'); await expect(invite).toHaveCount(0);
    await primary.getByRole('button').click();
    await page.getByRole('menuitem', {name: english ? 'Delete contact' : 'Șterge contactul'}).click();
    await page.getByRole('alertdialog').getByRole('button', {name: english ? 'Cancel' : 'Anulează'}).click();
    await expect(primary).toBeVisible();
    await primary.getByRole('button').click(); await page.getByRole('menuitem', {name: english ? 'Delete contact' : 'Șterge contactul'}).click();
    await page.getByRole('alertdialog').getByRole('button', {name: english ? 'Delete contact' : 'Șterge contactul'}).click();
    await expect(primary).toHaveCount(0);
    await page.getByRole('button', {name: english ? 'Edit vendor' : 'Editează furnizor'}).click();
    await expect(page.locator('#edit-vendor-email')).toHaveValue('updated@example.test');
  });
  test(`${english ? 'EN' : 'RO'} activity: complete scoped history, filters/reset, local invite/edit/template/lifecycle`, async ({page}) => {
    await page.goto(`${prefix}/vendors/construct-pro`);
    await page.getByRole('button', {name: english ? 'Edit vendor' : 'Editează furnizor'}).click();
    await page.locator('#edit-vendor-name').fill('Renamed vendor');
    await page.getByRole('button', {name: english ? 'Save changes' : 'Salvează modificările'}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button', {name: english ? 'Invite supplier' : 'Invită furnizor', exact: true}).click();
    await page.getByRole('dialog').getByRole('button', {name: english ? 'Send invitation' : 'Trimite invitația'}).click();
    await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button', {name: english ? 'Set up documents from templates' : 'Setează documente din șablon'}).click();
    const selector = page.getByRole('dialog');
    await selector.getByRole('checkbox', {name: english ? /^Maintenance services/ : /^Servicii de mentenanță/}).check();
    await selector.getByRole('button', {name: english ? /^Apply 1 / : /^Aplică 1 /}).click();
    await page.getByRole('dialog').getByRole('button', {name: english ? 'Apply templates' : 'Aplică șabloanele'}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.getByText(english ? 'View applicable requirements' : 'Vezi cerințele aplicabile')).toHaveCount(0);
    await page.getByRole('button', {name: english ? 'Add document' : 'Adaugă document', exact: true}).click();
    const upload = page.getByRole('dialog');
    await upload.locator('input[type=file]').setInputFiles({name: 'Insurance.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nlocal demo')});
    await upload.locator('#add-document-type').selectOption('insurance');
    await upload.getByRole('button', {name: english ? 'Upload and continue' : 'Încarcă și continuă'}).click();
    await expect(upload).toHaveCount(0);
    await page.getByRole('tab', {name: english ? 'Activity' : 'Activitate', exact: true}).click();
    await page.getByRole('combobox', {name: english ? 'Activities per page' : 'Activități pe pagină'}).selectOption('20');
    for (const type of ['vendor_edited', 'vendor_invited', 'template_applied']) await expect(page.locator(`[data-event-type="${type}"]`)).toHaveCount(1);
    await expect(page.locator('[data-vendor-event^="local-audit-"][data-event-type="document_upload"]')).toHaveCount(1);
    const dates = await page.locator('[data-vendor-event] time').evaluateAll((times) => times.map((time) => time.getAttribute('dateTime')!));
    expect(dates).toEqual([...dates].sort().reverse());
    await expect(page.locator('#vendor-activity')).not.toContainText('Global Clean Services');
    const search = page.getByRole('searchbox', {name: english ? 'Search activity' : 'Caută în activitate'});
    await search.fill(english ? '  TAX CERTIFICATE  ' : '  CERTIFICAT FISCAL  ');
    await openFilters(page);
    await page.locator('#vendor-activity-type').selectOption('document_upload');
    await expect(page.locator('[data-vendor-event]')).toHaveCount(1);
    await expect(page.getByRole('button', {name: english ? 'Filter (1)' : 'Filtrează (1)', exact: true})).toBeVisible();
    await page.getByRole('button', {name: english ? 'Reset' : 'Resetează', exact: true}).click();
    await expect(search).toHaveValue(english ? '  TAX CERTIFICATE  ' : '  CERTIFICAT FISCAL  ');
    await page.keyboard.press('Escape');
    await search.fill('');
    await page.getByRole('combobox', {name: english ? 'Activities per page' : 'Activități pe pagină'}).selectOption('5');
    await page.getByRole('button', {name: english ? 'Next page' : 'Pagina următoare'}).click();
    await expect(page.locator('#vendor-activity [aria-current="page"]')).toHaveText('2');
    await search.fill(english ? 'Vendor edited' : 'Furnizor editat');
    await expect(page.locator('#vendor-activity [aria-current="page"]')).toHaveText('1');
    await page.getByRole('navigation', {name: english ? 'Breadcrumb' : 'Navigare pe pagină'}).getByRole('link', {name: english ? 'Suppliers' : 'Furnizori'}).click();
    const row = page.locator('[data-vendor-id="construct-pro"]'); await row.getByRole('button').click();
    await page.getByRole('menuitem', {name: english ? 'Mark inactive' : 'Marchează ca inactiv'}).click();
    await row.getByRole('link').click(); await page.getByRole('tab', {name: english ? 'Activity' : 'Activitate', exact: true}).click();
    await expect(page.locator('[data-event-type="vendor_inactive"]')).toHaveCount(1);
    await page.getByRole('navigation', {name: english ? 'Application navigation' : 'Navigare în aplicație'}).getByRole('link', {name: english ? /^Notifications/ : /^Notificări/}).click();
    await expect(page.getByText(english ? 'Vendor marked inactive' : 'Furnizor dezactivat', {exact: true})).toBeVisible();
  });
  test(`${english ? 'EN' : 'RO'} notes: create/save/dirty guards/delete and company isolation`, async ({page}) => {
    await page.goto(`${prefix}/vendors`);
    await page.getByRole('link', {name: english ? 'Details for Construct Pro SRL' : 'Detalii pentru Construct Pro SRL'}).click();
    await page.getByRole('tab', {name: english ? 'Notes' : 'Note', exact: true}).click();
    await expect(page.getByText(english ? 'There are no notes for this vendor.' : 'Nu există notițe pentru acest furnizor.')).toBeVisible();
    await createNote(page, english, 'General discussions');
    const save = page.getByRole('button', {name: english ? 'Save changes' : 'Salvează modificările'});
    await expect(save).toBeDisabled();
    await page.getByRole('button', {name: english ? 'Create a thread' : 'Creează un thread'}).click();
    await expect(page.locator('[data-note-id]')).toHaveCount(1);
    await page.locator('#vendor-note-content').fill('Unsaved new draft');
    await page.getByRole('button', {name: english ? 'Create a thread' : 'Creează un thread'}).click();
    await page.getByRole('alertdialog').getByRole('button', {name: english ? 'Continue editing' : 'Continuă editarea'}).click();
    await expect(page.locator('#vendor-note-content')).toHaveValue('Unsaved new draft');
    await page.getByRole('tab', {name: english ? 'Contacts' : 'Contacte', exact: true}).click();
    await page.getByRole('alertdialog').getByRole('button', {name: english ? 'Discard changes' : 'Renunță la modificări'}).click();
    await page.getByRole('tab', {name: english ? 'Notes' : 'Note', exact: true}).click();
    await expect(page.locator('[data-note-id]')).toHaveCount(1);
    await createNote(page, english, 'Compliance');
    await page.locator('#vendor-note-content').fill('Unsaved');
    await page.locator('[data-note-id]').filter({hasText: 'General discussions'}).getByRole('button').first().click();
    const confirmation = page.getByRole('alertdialog');
    await expect(confirmation).toBeVisible();
    await confirmation.getByRole('button', {name: english ? 'Continue editing' : 'Continuă editarea'}).click();
    await expect(page.locator('#vendor-note-content')).toHaveValue('Unsaved');
    await page.getByRole('tab', {name: english ? 'Contacts' : 'Contacte', exact: true}).click();
    await confirmation.getByRole('button', {name: english ? 'Discard changes' : 'Renunță la modificări'}).click();
    await page.getByRole('tab', {name: english ? 'Notes' : 'Note', exact: true}).click();
    await expect(page.locator('#vendor-note-content')).toHaveValue('Content for General discussions');
    await page.locator('#vendor-note-title').fill(''); await expect(save).toBeDisabled();
    await page.locator('#vendor-note-title').fill('Updated general'); await save.click(); await expect(save).toBeDisabled();
    await page.locator('#vendor-note-content').fill('Dirty navigation');
    await page.getByRole('navigation', {name: english ? 'Application navigation' : 'Navigare în aplicație'}).getByRole('link', {name: english ? 'Documents' : 'Documente', exact: true}).click();
    await confirmation.getByRole('button', {name: english ? 'Continue editing' : 'Continuă editarea'}).click();
    await expect(page).toHaveURL(/vendors\/construct-pro$/);
    await page.evaluate(() => window.history.back()); await expect(confirmation).toBeVisible();
    await confirmation.getByRole('button', {name: english ? 'Continue editing' : 'Continuă editarea'}).click();
    await expect(page).toHaveURL(/vendors\/construct-pro$/);
    await page.evaluate(() => window.history.back()); await expect(confirmation).toBeVisible();
    await confirmation.getByRole('button', {name: english ? 'Discard changes' : 'Renunță la modificări'}).click();
    await expect(page).toHaveURL(new RegExp(`${prefix}/vendors$`));
    await page.getByRole('link', {name: english ? 'Details for Construct Pro SRL' : 'Detalii pentru Construct Pro SRL'}).click();
    await page.getByRole('tab', {name: english ? 'Notes' : 'Note', exact: true}).click();
    await expect(page.locator('#vendor-note-content')).toHaveValue('Content for General discussions');
    await page.locator('#vendor-note-content').fill('Dirty company change');
    await page.getByRole('button', {name: 'Demo Company SRL', exact: true}).click();
    const switcher = page.getByRole('dialog', {name: english ? 'Switch company' : 'Schimbă compania'});
    await switcher.getByRole('button', {name: /Global Clean Services/}).click();
    await confirmation.getByRole('button', {name: english ? 'Continue editing' : 'Continuă editarea'}).click();
    await page.getByRole('button', {name: 'Demo Company SRL', exact: true}).click();
    await switcher.getByRole('button', {name: /Global Clean Services/}).click();
    await confirmation.getByRole('button', {name: english ? 'Discard changes' : 'Renunță la modificări'}).click();
    await expect(page.locator('#vendor-notes')).toHaveCount(0);
    await expect(page.locator('[data-contact-id], [data-vendor-event]')).toHaveCount(0);
    await page.getByRole('button', {name: 'Global Clean Services', exact: true}).click();
    await page.getByRole('dialog').getByRole('button', {name: /Demo Company SRL/}).click();
    await page.getByRole('tab', {name: english ? 'Notes' : 'Note', exact: true}).click();
    for (const title of ['Updated general', 'Compliance']) {
      const thread = page.locator('[data-note-id]').filter({hasText: title});
      await thread.getByRole('button').last().click();
      await page.getByRole('menuitem', {name: english ? 'Delete thread' : 'Șterge thread-ul'}).click();
      await confirmation.getByRole('button', {name: english ? 'Delete thread' : 'Șterge thread-ul'}).click();
      await expect(thread).toHaveCount(0);
    }
    await expect(page.locator('#vendor-note-content')).toHaveCount(0);
    await expect(page.getByRole('button', {name: english ? 'Create the first note' : 'Creează prima notiță'})).toBeVisible();
  });
  test(`${english ? 'EN' : 'RO'} responsive tabs and safe invitation without contact email`, async ({page}) => {
    await page.goto(`${prefix}/vendors/construct-pro`);
    for (const width of [1448, 1024, 758, 600, 375, 320]) {
      await page.setViewportSize({width, height: width === 1448 ? 1086 : 812});
      for (const name of english ? ['Contacts', 'Activity', 'Notes'] : ['Contacte', 'Activitate', 'Note']) {
        await page.getByRole('tab', {name, exact: true}).click();
        await expect(page.getByRole('tabpanel')).toBeVisible();
        expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
      }
      await createNote(page, english, `Thread ${width}`);
      await expect(page.locator('#vendor-note-content')).toBeVisible();
      await page.getByRole('tab', {name: english ? 'Contacts' : 'Contacte', exact: true}).click();
      await page.getByRole('button', {name: english ? 'Add contact' : 'Adaugă contact', exact: true}).click();
      const drawer = page.getByRole('dialog');
      await drawer.getByRole('button', {name: english ? 'Add contact' : 'Adaugă contact', exact: true}).click();
      await expect(drawer.locator('#contact-name')).toBeFocused();
      expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
      await page.keyboard.press('Escape'); await expect(drawer).toHaveCount(0);
    }
    await page.goto(`${prefix}/vendors/alpha-construction`);
    await page.getByRole('button', {name: english ? 'Invite supplier' : 'Invită furnizor', exact: true}).click();
    await expect(page.locator('#invite-vendor-contact')).toBeDisabled();
    await expect(page.getByRole('dialog').getByRole('button', {name: english ? 'Send invitation' : 'Trimite invitația'})).toBeDisabled();
    await page.getByRole('dialog').getByRole('button', {name: english ? 'Add contact' : 'Adaugă contact', exact: true}).click();
    await expect(page.locator('#vendor-contacts')).toBeVisible();
  });
}

test('Notes protects browser Back in the popstate fallback without the Navigation API', async ({page}) => {
  await page.addInitScript(() => Object.defineProperty(window, 'navigation', {value: undefined, configurable: true}));
  await page.goto('/vendors');
  await page.getByRole('link', {name: 'Detalii pentru Construct Pro SRL'}).click();
  await page.getByRole('tab', {name: 'Note', exact: true}).click();
  await createNote(page, false, 'Saved fallback note');
  await page.locator('#vendor-note-content').fill('Unsaved browser Back');
  await page.evaluate(() => window.history.back());
  const confirmation = page.getByRole('alertdialog');
  await expect(confirmation).toBeVisible();
  await confirmation.getByRole('button', {name: 'Continuă editarea'}).click();
  await expect(page).toHaveURL(/vendors\/construct-pro$/);
  await expect(page.locator('#vendor-note-content')).toHaveValue('Unsaved browser Back');
  await page.getByRole('tab', {name: 'Contacte', exact: true}).click();
  await confirmation.getByRole('button', {name: 'Continuă editarea'}).click();
  await page.getByRole('navigation', {name: 'Navigare în aplicație'}).getByRole('link', {name: 'Documente', exact: true}).click();
  await confirmation.getByRole('button', {name: 'Renunță la modificări'}).click();
  await expect(page).toHaveURL(/\/documents$/);
  await page.goBack();
  await expect(page).toHaveURL(/vendors\/construct-pro$/);
  await page.getByRole('tab', {name: 'Note', exact: true}).click();
  await expect(page.locator('#vendor-note-content')).toHaveValue('Content for Saved fallback note');
  await page.locator('#vendor-note-content').fill('Unsaved again');
  await page.evaluate(() => window.history.back());
  await confirmation.getByRole('button', {name: 'Renunță la modificări'}).click();
  await expect(page).toHaveURL(/\/vendors$/);
  await page.getByRole('link', {name: 'Detalii pentru Construct Pro SRL'}).click();
  await page.getByRole('tab', {name: 'Note', exact: true}).click();
  await page.locator('#vendor-note-content').fill('Saved update');
  await page.getByRole('button', {name: 'Salvează modificările'}).click();
  await expect(page.getByRole('button', {name: 'Salvează modificările'})).toBeDisabled();
  await page.goBack();
  await expect(page).toHaveURL(/\/vendors$/);
});
