import type {NotificationsViewModel} from './types';

/** Fixed demo snapshot. It does not represent delivered notifications or persisted audit records. */
export const notificationsFixture: NotificationsViewModel = {
  referenceTime: '2026-09-27T12:00:00.000Z',
  user: {fullName: 'Andrei Popescu', initials: 'AP'},
  organization: {name: 'Demo Company SRL'},
  notifications: [
    {id: 'notice-reminder-1', type: 'reminder', title: {ro: 'Reminder trimis', en: 'Reminder sent'}, description: {ro: 'Reminder pentru expirarea certificatului fiscal către Construct Pro SRL', en: 'Expiry reminder for the tax certificate sent to Construct Pro SRL'}, vendorId: 'construct-pro', vendorName: 'Construct Pro SRL', documentId: 'construct-pro-tax-2024', documentName: {ro: 'Certificat fiscal', en: 'Tax certificate'}, occurredAt: '2026-09-27T10:24:00.000Z', isUnread: true, actor: 'user', actorName: 'Andrei Popescu'},
    {id: 'notice-upload-1', type: 'document_upload', title: {ro: 'Document încărcat', en: 'Document uploaded'}, description: {ro: 'Autorizație ISU încărcată pentru Global Clean Services', en: 'Fire safety authorization uploaded for Global Clean Services'}, vendorId: 'global-clean', vendorName: 'Global Clean Services', documentName: {ro: 'Autorizație ISU', en: 'Fire safety authorization'}, occurredAt: '2026-09-26T16:11:00.000Z', isUnread: false, actor: 'user', actorName: 'Maria Ionescu'},
    {id: 'notice-confirmed-1', type: 'document_confirmed', title: {ro: 'Document confirmat', en: 'Document confirmed'}, description: {ro: 'Certificat de înregistrare confirmat de Andrei Popescu pentru Tech Solutions SRL', en: 'Registration certificate confirmed by Andrei Popescu for Tech Solutions SRL'}, vendorId: 'tech-solutions', vendorName: 'Tech Solutions SRL', documentName: {ro: 'Certificat de înregistrare', en: 'Registration certificate'}, occurredAt: '2026-09-26T14:32:00.000Z', isUnread: false, actor: 'user', actorName: 'Andrei Popescu'},
    {id: 'notice-expiring-1', type: 'document_expiring', title: {ro: 'Se apropie termenul de expirare', en: 'Expiry is approaching'}, description: {ro: 'Notificare automată pentru Logistics Expert', en: 'Automatic notice for Logistics Expert'}, vendorId: 'logistics-expert', vendorName: 'Logistics Expert', documentName: {ro: 'Asigurare Răspundere Civilă', en: 'Liability insurance'}, occurredAt: '2026-09-25T11:10:00.000Z', isUnread: false, actor: 'system'},
    {id: 'notice-status-1', type: 'status_changed', title: {ro: 'Status schimbat', en: 'Status changed'}, description: {ro: 'Status document modificat în „În regulă” pentru Build & More SRL', en: 'Document status changed to “In good standing” for Build & More SRL'}, vendorId: 'build-more', vendorName: 'Build & More SRL', documentName: {ro: 'Adeverință D112', en: 'D112 certificate'}, occurredAt: '2026-09-24T09:18:00.000Z', isUnread: true, actor: 'user', actorName: 'Ioana Radu'},
    {id: 'notice-vendor-1', type: 'vendor_added', title: {ro: 'Furnizor adăugat', en: 'Supplier added'}, description: {ro: 'Furnizor nou adăugat în sistem: Green Energy SRL', en: 'New supplier added to the system: Green Energy SRL'}, vendorId: 'green-energy', vendorName: 'Green Energy SRL', occurredAt: '2026-09-22T08:00:00.000Z', isUnread: false, actor: 'user', actorName: 'Andrei Popescu'},
    {id: 'notice-reminder-2', type: 'reminder', title: {ro: 'Reminder trimis', en: 'Reminder sent'}, description: {ro: 'Reminder pentru documentele lipsă ale Build & More SRL', en: 'Reminder for missing documents at Build & More SRL'}, vendorId: 'build-more', vendorName: 'Build & More SRL', occurredAt: '2026-09-20T12:45:00.000Z', isUnread: false, actor: 'system'},
    {id: 'notice-missing-1', type: 'document_missing', title: {ro: 'Document lipsă', en: 'Missing document'}, description: {ro: 'Autorizația de mediu lipsește pentru Green Energy SRL', en: 'Environmental authorization is missing for Green Energy SRL'}, vendorId: 'green-energy', vendorName: 'Green Energy SRL', documentName: {ro: 'Autorizație mediu', en: 'Environmental authorization'}, occurredAt: '2026-09-05T07:10:00.000Z', isUnread: true, actor: 'system'},
    {id: 'notice-upload-old', type: 'document_upload', title: {ro: 'Document încărcat', en: 'Document uploaded'}, description: {ro: 'Certificat fiscal încărcat pentru Nova Energy SRL', en: 'Tax certificate uploaded for Nova Energy SRL'}, vendorId: 'nova-energy', vendorName: 'Nova Energy SRL', occurredAt: '2026-08-12T10:00:00.000Z', isUnread: false, actor: 'user', actorName: 'Andrei Popescu'},
    {id: 'notice-status-old', type: 'status_changed', title: {ro: 'Status schimbat', en: 'Status changed'}, description: {ro: 'Status furnizor actualizat pentru Prime Clean SRL', en: 'Supplier status updated for Prime Clean SRL'}, vendorId: 'prime-clean', vendorName: 'Prime Clean SRL', occurredAt: '2026-07-15T13:00:00.000Z', isUnread: false, actor: 'system'}
  ],
  auditEvents: [
    {id: 'audit-reminder-1', eventType: 'reminder', actorType: 'user', actorName: 'Andrei Popescu', action: {ro: 'Reminder trimis', en: 'Reminder sent'}, description: {ro: 'Reminder pentru expirarea documentului Certificat fiscal către Construct Pro SRL', en: 'Expiry reminder for Tax certificate sent to Construct Pro SRL'}, vendorId: 'construct-pro', documentId: 'construct-pro-tax-2024', occurredAt: '2026-09-27T10:24:00.000Z'},
    {id: 'audit-upload-1', eventType: 'document_upload', actorType: 'user', actorName: 'Maria Ionescu', action: {ro: 'Document încărcat', en: 'Document uploaded'}, description: {ro: 'Autorizație ISU încărcată pentru Global Clean Services', en: 'Fire safety authorization uploaded for Global Clean Services'}, vendorId: 'global-clean', occurredAt: '2026-09-26T16:11:00.000Z'},
    {id: 'audit-confirmed-1', eventType: 'document_confirmed', actorType: 'user', actorName: 'Andrei Popescu', action: {ro: 'Document confirmat', en: 'Document confirmed'}, description: {ro: 'Certificat de înregistrare confirmat pentru Tech Solutions SRL', en: 'Registration certificate confirmed for Tech Solutions SRL'}, vendorId: 'tech-solutions', occurredAt: '2026-09-26T14:32:00.000Z'},
    {id: 'audit-expiring-1', eventType: 'document_expiring', actorType: 'system', action: {ro: 'Se apropie termenul de expirare', en: 'Expiry is approaching'}, description: {ro: 'Notificare automată pentru Logistics Expert', en: 'Automatic notice for Logistics Expert'}, vendorId: 'logistics-expert', occurredAt: '2026-09-25T11:10:00.000Z'},
    {id: 'audit-status-1', eventType: 'status_changed', actorType: 'user', actorName: 'Ioana Radu', action: {ro: 'Status schimbat', en: 'Status changed'}, description: {ro: 'Status document modificat în „În regulă” pentru Build & More SRL', en: 'Document status changed to “In good standing” for Build & More SRL'}, vendorId: 'build-more', occurredAt: '2026-09-24T09:18:00.000Z'},
    {id: 'audit-vendor-1', eventType: 'vendor_added', actorType: 'user', actorName: 'Andrei Popescu', action: {ro: 'Furnizor adăugat', en: 'Supplier added'}, description: {ro: 'Furnizor nou adăugat în sistem: Green Energy SRL', en: 'New supplier added to the system: Green Energy SRL'}, vendorId: 'green-energy', occurredAt: '2026-09-22T08:00:00.000Z'},
    {id: 'audit-missing-1', eventType: 'document_missing', actorType: 'system', action: {ro: 'Document lipsă', en: 'Missing document'}, description: {ro: 'Autorizația de mediu lipsește pentru Green Energy SRL', en: 'Environmental authorization is missing for Green Energy SRL'}, vendorId: 'green-energy', occurredAt: '2026-09-05T07:10:00.000Z'},
    {id: 'audit-older', eventType: 'document_upload', actorType: 'system', action: {ro: 'Import document', en: 'Document import'}, description: {ro: 'Document demonstrativ importat pentru Nova Energy SRL', en: 'Demo document imported for Nova Energy SRL'}, vendorId: 'nova-energy', occurredAt: '2026-08-12T10:00:00.000Z'}
  ],
  expiringDocuments: [
    {id: 'expiry-1', vendorId: 'construct-pro', vendorName: 'Construct Pro SRL', documentName: {ro: 'Certificat fiscal', en: 'Tax certificate'}, expiresAt: '2026-10-02', daysRemaining: 5, status: 'expiring'},
    {id: 'expiry-2', vendorId: 'global-clean', vendorName: 'Global Clean Services', documentName: {ro: 'Autorizație ISU', en: 'Fire safety authorization'}, expiresAt: '2026-10-15', daysRemaining: 18, status: 'expiring'},
    {id: 'expiry-3', vendorId: 'tech-solutions', vendorName: 'Tech Solutions SRL', documentName: {ro: 'Certificat de înregistrare', en: 'Registration certificate'}, expiresAt: '2026-10-20', daysRemaining: 23, status: 'expiring'},
    {id: 'expiry-4', vendorId: 'logistics-expert', vendorName: 'Logistics Expert', documentName: {ro: 'Asigurare Răspundere Civilă', en: 'Liability insurance'}, expiresAt: '2026-10-23', daysRemaining: 26, status: 'expiring'},
    {id: 'expiry-5', vendorId: 'food-supplies', vendorName: 'Food Supplies SRL', documentName: {ro: 'Certificat sanitar', en: 'Sanitary certificate'}, expiresAt: '2026-10-26', daysRemaining: 29, status: 'expiring'}
  ],
  missingDocuments: [
    {id: 'missing-1', vendorId: 'build-more', vendorName: 'Build & More SRL', documentName: {ro: 'Dovadă plata taxe', en: 'Proof of tax payment'}, requirement: {ro: 'Conformitate fiscală', en: 'Tax compliance'}, dueAt: '2026-09-15', status: 'missing'},
    {id: 'missing-2', vendorId: 'green-energy', vendorName: 'Green Energy SRL', documentName: {ro: 'Autorizație mediu', en: 'Environmental authorization'}, requirement: {ro: 'Mediu', en: 'Environment'}, dueAt: '2026-09-22', status: 'missing'},
    {id: 'missing-3', vendorId: 'logistics-expert', vendorName: 'Logistics Expert', documentName: {ro: 'Politică SSM', en: 'Workplace safety policy'}, requirement: {ro: 'Sănătate și securitate', en: 'Health and safety'}, dueAt: '2026-10-05', status: 'missing'}
  ]
};
